name: Main

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  id-token: write # REQUIRED for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Install depencies
        run: bun install
      - name: Check format
        run: bun format:check
      - name: Lint
        run: bun lint
      #   - name: Test
      #     run: bun test
      - name: Generate static files
        run: bun generate
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  infra:
    runs-on: ubuntu-latest

    outputs:
      static-content-deploy-role-arn: ${{ steps.set-output.outputs.role_arn }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2

      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./aws/stornoway.yml
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::230767735088:role/cfdeploy-role
          aws-region: eu-central-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ./aws/stornoway.yml \
            --stack-name stornoway \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides DomainName=cv.molnarbence.dev

      - name: Set output variable
        id: set-output
        run: echo "role_arn=$(aws cloudformation describe-stacks --stack-name stornoway --query "Stacks[0].Outputs[?OutputKey=='StaticContentDeployRoleArn'].OutputValue" --output text)" >> $GITHUB_OUTPUT

  upload-to-s3:
    needs:
      - build
      - infra
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.infra.outputs.static-content-deploy-role-arn }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./ s3://cv.molnarbence.dev --delete

      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
